### ISSUE TITLE
Citadel + Alex's Mobs crash on 1.19 (not .1 or .2)

### ISSUE THREAD

**Issue by Cyberian10** [AlexModGuy/Citadel#81] opened 2022-09-11 19:14 UTC
Every time I start the game, I get the "Failed to Load Correctly. java.lang.reflect.InvocationTargetException: null" error. I'm using forge 41.1.0. Here's my log:

https://pastebin.com/7UepdmPk

**Comment by uhloin** [comment] 2022-09-12 07:09
I also have crash for newest version 1.12.9 with alex's mobs, biomes of plenty and biomes you go.
stderr:

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.15/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldError: COMPOUND_TAG
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.15/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:145)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	... 13 more
Caused by: java.lang.NoSuchFieldError: COMPOUND_TAG
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.<clinit>(LivingEntity.java:155)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:252)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:665)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.lambda$run$0(Main.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Daltaxy** [comment] 2022-09-12 15:23
same issue here, but reverting back to the older version didn't fix the issue for me. Could be an incompatibility with architectury, moonlight, or delightful ? I updated them at the same time and my game won't start now.
https://gist.github.com/Daltaxy/2f5690e9b386013642a984505257a8d6

**Comment by Baggytrousers27** [comment] 2022-09-12 18:07
Piggy backing on this because 1.12.10 from 30 mins ago still crashes.
1.12.7 Seems to still work though.

**Comment by Daltaxy** [comment] 2022-09-12 18:53
yep, last mod version still crashes on 1.19.2.

**Comment by uhloin** [comment] 2022-09-13 06:40
I use 1.12.7 and it works.

**Comment by uhloin** [comment] 2022-09-13 06:46
1.12.10 wrote the same stderr except one thing: there are no substring "<clinit>".

**Comment by desbarmitar** [comment] 2022-09-13 22:57
Downgrading to `citadel-1.12.7-1.19` fixes the issue :)
by @NielsPilgaard

**Comment by AlexModGuy** [comment] 2022-09-14 00:27
fixed in 1.12.11.

**Closed by AlexModGuy** 2022-09-14 00:27 UTC
