### ISSUE TITLE
Biome source mixin conflict with Biolith (potentially Terrablender as well)

### ISSUE THREAD

**Issue by Su5eD** [AlexModGuy/Citadel#136] opened 2023-10-21 21:25 UTC
An issue has been reported to me on Sinytra/Connector#396 regarding Alex's Caves biomes not generating when Biolith is installed. I've tracked this down to a mixin conflict targetting the `MultiNoiseBiomeSource` class.

### The isssue

- Biolith is deliberately configured to always [inject last](https://github.com/TerraformersMC/Biolith/blob/078706fe496f611e8492204c2d29001148160525/src/main/java/com/terraformersmc/biolith/impl/mixin/MixinMultiNoiseBiomeSource.java#L28) to ensure compatibility with terrablender.
- Terrablender's [mixin](https://github.com/Glitchfiend/TerraBlender/blob/a3fd3a82f0cb3b5a4da724e00e8e0783f7e78bf9/Common/src/main/java/terrablender/mixin/MixinMultiNoiseBiomeSource.java#L31) uses default priority, which means "lottery" decides who comes out on top.
- Citadel's [mixin](https://github.com/AlexModGuy/Citadel/blob/718086e6fdbe9dca33e69dbbccde1b336d291965/src/main/java/com/github/alexthe666/citadel/mixin/MultiNoiseBiomeSourceMixin.java#L21) also uses default priority, but only cancels conditionally.

Terrablender always cancels, just like Biolith, so it's enough that this race condition ends in terrablender injecting last, and alex's caves will never be able to run its replacements.
I don't know how the backing `SortedSet` decides the order of equal elements, it could be the hashcode, name, anything.
 But right now, terrablender goes first, and so Citadel has a change to run its replacements where needed. Biolith, on the other hand, will always break as explained above.

![](https://github.com/AlexModGuy/Citadel/assets/51261569/0d4c1504-c52b-4467-8a7d-0cc8af21ce1d)

### The solution

Since citadel only cancels where neded, it's enough that the mixin priority be lowered below biolith's one, and it should be guaranteed to work.

**Comment by peepeepoopoocaca** [comment] 2023-10-22 04:13
I can confirm that Terrablender seems to be causing this issue for me consistently. Enabling Terrablender, even without mods that add in new biomes, prevents caves from Alex's Caves from generating.

**Comment by AlexModGuy** [comment] 2023-10-23 17:59
What would you recommend to set the priority to?

**Comment by AlexModGuy** [comment] 2023-10-23 18:06
fixed in 2.4.6

**Closed by AlexModGuy** 2023-10-23 18:06 UTC
